language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "node"

sudo: false

install:
  - "npm install"

cache:
    npm: false
    directories:
        - $HOME/.npm

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then npm update -g npm; fi
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then node `npm prefix -g`/node_modules/npm/bin/npm-cli.js i -g npm@latest; fi

os:
  - "linux"
  - "osx"
  - "windows"
